### ISSUE TITLE
Android: Failed to find module:"nativescript:oauth",relative to: /app/tns_modules/

### ISSUE THREAD

**Issue by Gerstalexej** [alexziskind1/nativescript-oauth#15]
I created a test project to try this module. (Like Alexander Ziskind does in his youtube video)
When I call `tnsOAuthModule.initFacebook(facebookInitOptions);` I get an exception that starts with  

> Error: com.tns.NativescriptException: Failed to find module:"nativescript:oauth",relative to: 
/app/tns_modules/

This seems similar to the problem this guy was having:
http://stackoverflow.com/questions/39964752/nativescriptoauth-not-working

But in my case, the import statement `import * as tnsOAuthModule from 'nativescript-oauth';`  and ` var facebookInitOptions : tnsOAuthModule.ITnsOAuthOptionsFacebook = {...}` work fine, it's only when I call `tnsOAuthModule.initFacebook(facebookInitOptions);` that I get this error.

**Comment by alexziskind1** [comment]
This has been "fixed". I've updated the package.json files of both demo and demo-angular projects to point to the npm repo for nativescript-oauth instead of local path (which wasn't working for some reason).
I've also updated to NativeScript 2.5

**Comment by Gerstalexej** [comment]
I installed and uninstalled using npm but the problem persists. (Also, it happens whether or notI call nsOAuthModule.initFacebook(facebookInitOptions);, it even happens when I comment everything out related to nativescipt-oauth)

**Comment by alexziskind1** [comment]
@Gerstalexej are you trying to add nativescript-oauth to your own project or are you trying to run the demo?

**Comment by Gerstalexej** [comment]
Sorry for not telling, this is about my own project

**Comment by alexziskind1** [comment]
Try doing this:

Create a new NativeScript project
```
tns create tnsoauthtest --tsc
```

```
cd tnsoauthtest
```

```
rm -rf platforms node_modules
```

```
npm install nativescript-oauth --save
```

Edit the app.ts file:
```ts
import "./bundle-config";
import * as app from 'application';

import * as tnsOauth from "nativescript-oauth"

let fo: tnsOauth.ITnsOAuthOptionsFacebook = {
    clientId: '',
    clientSecret: '',
    scope: []
};

tnsOauth.initFacebook(fo);

app.start({ moduleName: 'main-page' });
```

Back on the command line
```
tsc
```

This shouldn't give any output, especially no errors.

**Comment by Gerstalexej** [comment]
I get this: 
![image](https://cloud.githubusercontent.com/assets/6694504/22955004/212e6cda-f31a-11e6-9e89-49a227563dc5.png)

(Had to search half the internet to solve this in my personal project)

Also, this happens in vs code:

![image](https://cloud.githubusercontent.com/assets/6694504/22955061/781f1ddc-f31a-11e6-9fe0-7eac139b60f5.png)

Also,, in my personal project, when I run tsc no errors pop up; it's just when running the app in an emulator I get all these errors when the app crashes in the emulator

**Comment by alexziskind1** [comment]
Great. Can you push this sample app to a repository so I can take a look?
